// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNSnGx2EwM3ATUPBbHKuOTmWYSx1Hpofg',
    appId: '1:820774274057:web:7ee711e7e96f9a356624d8',
    messagingSenderId: '820774274057',
    projectId: 'flutter-application-2-a7612',
    authDomain: 'flutter-application-2-a7612.firebaseapp.com',
    storageBucket: 'flutter-application-2-a7612.appspot.com',
    measurementId: 'G-2NHDV1TYF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFZoxESi9CVt0MECAlNtDjOr8CM2dT2I',
    appId: '1:820774274057:android:61fb0bc8a805ed836624d8',
    messagingSenderId: '820774274057',
    projectId: 'flutter-application-2-a7612',
    storageBucket: 'flutter-application-2-a7612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ3awVmJl290tMma2UjG-zURoFrJPqftA',
    appId: '1:820774274057:ios:9c0e38cfce135d556624d8',
    messagingSenderId: '820774274057',
    projectId: 'flutter-application-2-a7612',
    storageBucket: 'flutter-application-2-a7612.appspot.com',
    iosClientId: '820774274057-hj87cn2oas9ki2vtbpckcc0vkh053jvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ3awVmJl290tMma2UjG-zURoFrJPqftA',
    appId: '1:820774274057:ios:95b31c36a726dd9e6624d8',
    messagingSenderId: '820774274057',
    projectId: 'flutter-application-2-a7612',
    storageBucket: 'flutter-application-2-a7612.appspot.com',
    iosClientId: '820774274057-3g290snl4b5jg5b0kjdurvlbng2m2d07.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
